export type CountryEntry = {
  slug: string;
  name: string;
  emoji: string;
};

export type CityEntry = {
  slug: string;
  name: string;
};

export const countries: CountryEntry[] = [
  { slug: "switzerland", name: "Switzerland", emoji: "🇨🇭" },
  { slug: "germany", name: "Germany", emoji: "🇩🇪" },
  { slug: "france", name: "France", emoji: "🇫🇷" },
  { slug: "italy", name: "Italy", emoji: "🇮🇹" },
  { slug: "spain", name: "Spain", emoji: "🇪🇸" },
  { slug: "united-kingdom", name: "United Kingdom", emoji: "🇬🇧" },
  { slug: "netherlands", name: "Netherlands", emoji: "🇳🇱" },
  { slug: "belgium", name: "Belgium", emoji: "🇧🇪" },
  { slug: "austria", name: "Austria", emoji: "🇦🇹" },
  { slug: "sweden", name: "Sweden", emoji: "🇸🇪" },
  { slug: "norway", name: "Norway", emoji: "🇳🇴" },
  { slug: "denmark", name: "Denmark", emoji: "🇩🇰" },
  { slug: "finland", name: "Finland", emoji: "🇫🇮" },
  { slug: "poland", name: "Poland", emoji: "🇵🇱" },
  { slug: "czech-republic", name: "Czech Republic", emoji: "🇨🇿" },
  { slug: "hungary", name: "Hungary", emoji: "🇭🇺" },
  { slug: "greece", name: "Greece", emoji: "🇬🇷" },
  { slug: "portugal", name: "Portugal", emoji: "🇵🇹" },
  { slug: "ireland", name: "Ireland", emoji: "🇮🇪" },
  { slug: "russia", name: "Russia", emoji: "🇷🇺" },
  { slug: "ukraine", name: "Ukraine", emoji: "🇺🇦" },
  { slug: "belarus", name: "Belarus", emoji: "🇧🇾" },
  { slug: "kazakhstan", name: "Kazakhstan", emoji: "🇰🇿" },
  { slug: "azerbaijan", name: "Azerbaijan", emoji: "🇦🇿" },
  { slug: "armenia", name: "Armenia", emoji: "🇦🇲" },
  { slug: "georgia", name: "Georgia", emoji: "🇬🇪" },
  { slug: "moldova", name: "Moldova", emoji: "🇲🇩" },
  { slug: "latvia", name: "Latvia", emoji: "🇱🇻" },
  { slug: "lithuania", name: "Lithuania", emoji: "🇱🇹" },
  { slug: "estonia", name: "Estonia", emoji: "🇪🇪" },
  { slug: "romania", name: "Romania", emoji: "🇷🇴" },
  { slug: "bulgaria", name: "Bulgaria", emoji: "🇧🇬" },
  { slug: "serbia", name: "Serbia", emoji: "🇷🇸" },
  { slug: "croatia", name: "Croatia", emoji: "🇭🇷" },
  { slug: "slovenia", name: "Slovenia", emoji: "🇸🇮" },
  { slug: "slovakia", name: "Slovakia", emoji: "🇸🇰" },
  { slug: "bosnia-and-herzegovina", name: "Bosnia and Herzegovina", emoji: "🇧🇦" },
  { slug: "montenegro", name: "Montenegro", emoji: "🇲🇪" },
  { slug: "north-macedonia", name: "North Macedonia", emoji: "🇲🇰" },
  { slug: "albania", name: "Albania", emoji: "🇦🇱" },
  { slug: "cyprus", name: "Cyprus", emoji: "🇨🇾" },
  { slug: "malta", name: "Malta", emoji: "🇲🇹" },
  { slug: "iceland", name: "Iceland", emoji: "🇮🇸" },
  { slug: "luxembourg", name: "Luxembourg", emoji: "🇱🇺" },
  { slug: "monaco", name: "Monaco", emoji: "🇲🇨" },
  { slug: "andorra", name: "Andorra", emoji: "🇦🇩" },
  { slug: "san-marino", name: "San Marino", emoji: "🇸🇲" },
  { slug: "liechtenstein", name: "Liechtenstein", emoji: "🇱🇮" },
  { slug: "kyrgyzstan", name: "Kyrgyzstan", emoji: "🇰🇬" },
  { slug: "tajikistan", name: "Tajikistan", emoji: "🇹🇯" },
  { slug: "turkmenistan", name: "Turkmenistan", emoji: "🇹🇲" },
  { slug: "uzbekistan", name: "Uzbekistan", emoji: "🇺🇿" },
];

export const citiesByCountry: Record<string, CityEntry[]> = {
  switzerland: [
    { slug: "zurich", name: "Zurich" },
    { slug: "geneva", name: "Geneva" },
    { slug: "basel", name: "Basel" },
    { slug: "bern", name: "Bern" },
    { slug: "lausanne", name: "Lausanne" },
    { slug: "lugano", name: "Lugano" },
  ],
  germany: [
    { slug: "berlin", name: "Berlin" },
    { slug: "munich", name: "Munich" },
    { slug: "hamburg", name: "Hamburg" },
    { slug: "frankfurt", name: "Frankfurt" },
    { slug: "cologne", name: "Cologne" },
    { slug: "stuttgart", name: "Stuttgart" },
  ],
  france: [
    { slug: "paris", name: "Paris" },
    { slug: "marseille", name: "Marseille" },
    { slug: "lyon", name: "Lyon" },
    { slug: "toulouse", name: "Toulouse" },
    { slug: "nice", name: "Nice" },
    { slug: "bordeaux", name: "Bordeaux" },
  ],
  italy: [
    { slug: "rome", name: "Rome" },
    { slug: "milan", name: "Milan" },
    { slug: "naples", name: "Naples" },
    { slug: "turin", name: "Turin" },
    { slug: "venice", name: "Venice" },
    { slug: "florence", name: "Florence" },
  ],
  spain: [
    { slug: "madrid", name: "Madrid" },
    { slug: "barcelona", name: "Barcelona" },
    { slug: "valencia", name: "Valencia" },
    { slug: "seville", name: "Seville" },
    { slug: "malaga", name: "Malaga" },
    { slug: "bilbao", name: "Bilbao" },
  ],
  "united-kingdom": [
    { slug: "london", name: "London" },
    { slug: "manchester", name: "Manchester" },
    { slug: "edinburgh", name: "Edinburgh" },
    { slug: "birmingham", name: "Birmingham" },
    { slug: "glasgow", name: "Glasgow" },
    { slug: "bristol", name: "Bristol" },
  ],
  netherlands: [
    { slug: "amsterdam", name: "Amsterdam" },
    { slug: "rotterdam", name: "Rotterdam" },
    { slug: "the-hague", name: "The Hague" },
    { slug: "utrecht", name: "Utrecht" },
    { slug: "eindhoven", name: "Eindhoven" },
  ],
  belgium: [
    { slug: "brussels", name: "Brussels" },
    { slug: "antwerp", name: "Antwerp" },
    { slug: "ghent", name: "Ghent" },
    { slug: "bruges", name: "Bruges" },
    { slug: "liege", name: "Liège" },
  ],
  austria: [
    { slug: "vienna", name: "Vienna" },
    { slug: "graz", name: "Graz" },
    { slug: "salzburg", name: "Salzburg" },
    { slug: "innsbruck", name: "Innsbruck" },
    { slug: "linz", name: "Linz" },
  ],
  sweden: [
    { slug: "stockholm", name: "Stockholm" },
    { slug: "gothenburg", name: "Gothenburg" },
    { slug: "malmo", name: "Malmö" },
    { slug: "uppsala", name: "Uppsala" },
    { slug: "linkoping", name: "Linköping" },
  ],
  norway: [
    { slug: "oslo", name: "Oslo" },
    { slug: "bergen", name: "Bergen" },
    { slug: "trondheim", name: "Trondheim" },
    { slug: "stavanger", name: "Stavanger" },
    { slug: "tromso", name: "Tromsø" },
  ],
  denmark: [
    { slug: "copenhagen", name: "Copenhagen" },
    { slug: "aarhus", name: "Aarhus" },
    { slug: "odense", name: "Odense" },
    { slug: "aalborg", name: "Aalborg" },
    { slug: "esbjerg", name: "Esbjerg" },
  ],
  finland: [
    { slug: "helsinki", name: "Helsinki" },
    { slug: "espoo", name: "Espoo" },
    { slug: "tampere", name: "Tampere" },
    { slug: "turku", name: "Turku" },
    { slug: "oulu", name: "Oulu" },
  ],
  poland: [
    { slug: "warsaw", name: "Warsaw" },
    { slug: "krakow", name: "Kraków" },
    { slug: "wroclaw", name: "Wrocław" },
    { slug: "gdansk", name: "Gdańsk" },
    { slug: "poznan", name: "Poznań" },
  ],
  "czech-republic": [
    { slug: "prague", name: "Prague" },
    { slug: "brno", name: "Brno" },
    { slug: "ostrava", name: "Ostrava" },
    { slug: "plzen", name: "Plzeň" },
    { slug: "olomouc", name: "Olomouc" },
  ],
  hungary: [
    { slug: "budapest", name: "Budapest" },
    { slug: "debrecen", name: "Debrecen" },
    { slug: "szeged", name: "Szeged" },
    { slug: "miskolc", name: "Miskolc" },
    { slug: "pecs", name: "Pécs" },
  ],
  greece: [
    { slug: "athens", name: "Athens" },
    { slug: "thessaloniki", name: "Thessaloniki" },
    { slug: "patras", name: "Patras" },
    { slug: "heraklion", name: "Heraklion" },
    { slug: "larissa", name: "Larissa" },
  ],
  portugal: [
    { slug: "lisbon", name: "Lisbon" },
    { slug: "porto", name: "Porto" },
    { slug: "faro", name: "Faro" },
    { slug: "braga", name: "Braga" },
    { slug: "coimbra", name: "Coimbra" },
  ],
  ireland: [
    { slug: "dublin", name: "Dublin" },
    { slug: "cork", name: "Cork" },
    { slug: "galway", name: "Galway" },
    { slug: "limerick", name: "Limerick" },
    { slug: "waterford", name: "Waterford" },
  ],
  russia: [
    { slug: "astrakhan", name: "Astrakhan" },
    { slug: "barnaul", name: "Barnaul" },
    { slug: "chechen-republic", name: "Chechen Republic" },
    { slug: "chelyabinsk", name: "Chelyabinsk" },
    { slug: "cherkessk", name: "Cherkessk" },
    { slug: "dagestan", name: "Dagestan" },
    { slug: "grozny", name: "Grozny" },
    { slug: "ingushetia", name: "Ingushetia" },
    { slug: "irkutsk", name: "Irkutsk" },
    { slug: "kaliningrad", name: "Kaliningrad" },
    { slug: "kazan", name: "Kazan" },
    { slug: "kemerovo", name: "Kemerovo" },
    { slug: "khabarovsk", name: "Khabarovsk" },
    { slug: "krasnodar", name: "Krasnodar" },
    { slug: "krasnoyarsk", name: "Krasnoyarsk" },
    { slug: "magas", name: "Magas" },
    { slug: "makhachkala", name: "Makhachkala" },
    { slug: "maykop", name: "Maykop" },
    { slug: "moscow", name: "Moscow" },
    { slug: "murmansk", name: "Murmansk" },
    { slug: "nalchik", name: "Nalchik" },
    { slug: "nazran", name: "Nazran" },
    { slug: "nizhny-novgorod", name: "Nizhny Novgorod" },
    { slug: "novosibirsk", name: "Novosibirsk" },
    { slug: "omsk", name: "Omsk" },
    { slug: "perm", name: "Perm" },
    { slug: "pyatigorsk", name: "Pyatigorsk" },
    { slug: "rostov-on-don", name: "Rostov-on-Don" },
    { slug: "ryazan", name: "Ryazan" },
    { slug: "saint-petersburg", name: "Saint Petersburg" },
    { slug: "samara", name: "Samara" },
    { slug: "saratov", name: "Saratov" },
    { slug: "sochi", name: "Sochi" },
    { slug: "stavropol", name: "Stavropol" },
    { slug: "tatarstan", name: "Tatarstan" },
    { slug: "tomsk", name: "Tomsk" },
    { slug: "tula", name: "Tula" },
    { slug: "tyumen", name: "Tyumen" },
    { slug: "ufa", name: "Ufa" },
    { slug: "vladikavkaz", name: "Vladikavkaz" },
    { slug: "vladivostok", name: "Vladivostok" },
    { slug: "volgograd", name: "Volgograd" },
    { slug: "voronezh", name: "Voronezh" },
    { slug: "yekaterinburg", name: "Yekaterinburg" },
    { slug: "yaroslavl", name: "Yaroslavl" },
  ],
  ukraine: [
    { slug: "kyiv", name: "Kyiv" },
    { slug: "lviv", name: "Lviv" },
    { slug: "odesa", name: "Odesa" },
    { slug: "kharkiv", name: "Kharkiv" },
    { slug: "dnipro", name: "Dnipro" },
    { slug: "zaporizhzhia", name: "Zaporizhzhia" },
  ],
  belarus: [
    { slug: "minsk", name: "Minsk" },
    { slug: "brest", name: "Brest" },
    { slug: "grodno", name: "Grodno" },
    { slug: "gomel", name: "Gomel" },
    { slug: "mogilev", name: "Mogilev" },
  ],
  kazakhstan: [
    { slug: "almaty", name: "Almaty" },
    { slug: "nur-sultan", name: "Nur-Sultan" },
    { slug: "shymkent", name: "Shymkent" },
    { slug: "karaganda", name: "Karaganda" },
    { slug: "aktobe", name: "Aktobe" },
  ],
  azerbaijan: [
    { slug: "baku", name: "Baku" },
    { slug: "ganja", name: "Ganja" },
    { slug: "sumqayit", name: "Sumqayit" },
    { slug: "mingachevir", name: "Mingachevir" },
    { slug: "lankaran", name: "Lankaran" },
  ],
  armenia: [
    { slug: "yerevan", name: "Yerevan" },
    { slug: "gyumri", name: "Gyumri" },
    { slug: "vanadzor", name: "Vanadzor" },
    { slug: "vagharshapat", name: "Vagharshapat" },
    { slug: "hrazdan", name: "Hrazdan" },
  ],
  georgia: [
    { slug: "tbilisi", name: "Tbilisi" },
    { slug: "batumi", name: "Batumi" },
    { slug: "kutaisi", name: "Kutaisi" },
    { slug: "rustavi", name: "Rustavi" },
    { slug: "zugdidi", name: "Zugdidi" },
  ],
  moldova: [
    { slug: "chisinau", name: "Chisinau" },
    { slug: "tiraspol", name: "Tiraspol" },
    { slug: "balti", name: "Balti" },
    { slug: "cahul", name: "Cahul" },
    { slug: "orhei", name: "Orhei" },
  ],
  latvia: [
    { slug: "riga", name: "Riga" },
    { slug: "daugavpils", name: "Daugavpils" },
    { slug: "liepaja", name: "Liepāja" },
    { slug: "jelgava", name: "Jelgava" },
    { slug: "jurmala", name: "Jūrmala" },
  ],
  lithuania: [
    { slug: "vilnius", name: "Vilnius" },
    { slug: "kaunas", name: "Kaunas" },
    { slug: "klaipeda", name: "Klaipėda" },
    { slug: "siauliai", name: "Šiauliai" },
    { slug: "panevezys", name: "Panevėžys" },
  ],
  estonia: [
    { slug: "tallinn", name: "Tallinn" },
    { slug: "tartu", name: "Tartu" },
    { slug: "narva", name: "Narva" },
    { slug: "parnu", name: "Pärnu" },
    { slug: "viljandi", name: "Viljandi" },
  ],
  romania: [
    { slug: "bucharest", name: "Bucharest" },
    { slug: "cluj-napoca", name: "Cluj-Napoca" },
    { slug: "timisoara", name: "Timișoara" },
    { slug: "iasi", name: "Iași" },
    { slug: "brasov", name: "Brașov" },
  ],
  bulgaria: [
    { slug: "sofia", name: "Sofia" },
    { slug: "plovdiv", name: "Plovdiv" },
    { slug: "varna", name: "Varna" },
    { slug: "burgas", name: "Burgas" },
    { slug: "ruse", name: "Ruse" },
  ],
  serbia: [
    { slug: "belgrade", name: "Belgrade" },
    { slug: "novi-sad", name: "Novi Sad" },
    { slug: "nis", name: "Niš" },
    { slug: "kragujevac", name: "Kragujevac" },
    { slug: "subotica", name: "Subotica" },
  ],
  croatia: [
    { slug: "zagreb", name: "Zagreb" },
    { slug: "split", name: "Split" },
    { slug: "dubrovnik", name: "Dubrovnik" },
    { slug: "rijeka", name: "Rijeka" },
    { slug: "osijek", name: "Osijek" },
  ],
  slovenia: [
    { slug: "ljubljana", name: "Ljubljana" },
    { slug: "maribor", name: "Maribor" },
    { slug: "celje", name: "Celje" },
    { slug: "kranj", name: "Kranj" },
    { slug: "novo-mesto", name: "Novo Mesto" },
  ],
  slovakia: [
    { slug: "bratislava", name: "Bratislava" },
    { slug: "kosice", name: "Košice" },
    { slug: "presov", name: "Prešov" },
    { slug: "nitra", name: "Nitra" },
    { slug: "zilina", name: "Žilina" },
  ],
  "bosnia-and-herzegovina": [
    { slug: "sarajevo", name: "Sarajevo" },
    { slug: "banja-luka", name: "Banja Luka" },
    { slug: "mostar", name: "Mostar" },
    { slug: "tuzla", name: "Tuzla" },
    { slug: "zenica", name: "Zenica" },
  ],
  montenegro: [
    { slug: "podgorica", name: "Podgorica" },
    { slug: "niksic", name: "Nikšić" },
    { slug: "herceg-novi", name: "Herceg Novi" },
    { slug: "bar", name: "Bar" },
    { slug: "budva", name: "Budva" },
  ],
  "north-macedonia": [
    { slug: "skopje", name: "Skopje" },
    { slug: "bitola", name: "Bitola" },
    { slug: "ohrid", name: "Ohrid" },
    { slug: "kumanovo", name: "Kumanovo" },
    { slug: "tetovo", name: "Tetovo" },
  ],
  albania: [
    { slug: "tirana", name: "Tirana" },
    { slug: "durres", name: "Durrës" },
    { slug: "vlore", name: "Vlorë" },
    { slug: "shkoder", name: "Shkodër" },
    { slug: "elbasan", name: "Elbasan" },
  ],
  cyprus: [
    { slug: "nicosia", name: "Nicosia" },
    { slug: "limassol", name: "Limassol" },
    { slug: "larnaca", name: "Larnaca" },
    { slug: "paphos", name: "Paphos" },
    { slug: "famagusta", name: "Famagusta" },
  ],
  malta: [
    { slug: "valletta", name: "Valletta" },
    { slug: "birkirkara", name: "Birkirkara" },
    { slug: "mosta", name: "Mosta" },
    { slug: "sliema", name: "Sliema" },
    { slug: "st-julians", name: "St. Julian's" },
  ],
  iceland: [
    { slug: "reykjavik", name: "Reykjavik" },
    { slug: "akureyri", name: "Akureyri" },
    { slug: "keflavik", name: "Keflavik" },
    { slug: "hafnarfjordur", name: "Hafnarfjörður" },
    { slug: "selfoss", name: "Selfoss" },
  ],
  luxembourg: [
    { slug: "luxembourg-city", name: "Luxembourg" },
    { slug: "esch-sur-alzette", name: "Esch-sur-Alzette" },
    { slug: "differdange", name: "Differdange" },
    { slug: "dudelange", name: "Dudelange" },
    { slug: "ettelbruck", name: "Ettelbruck" },
  ],
  monaco: [
    { slug: "monaco", name: "Monaco" },
    { slug: "fontvieille", name: "Fontvieille" },
    { slug: "la-condamine", name: "La Condamine" },
    { slug: "monte-carlo", name: "Monte Carlo" },
  ],
  andorra: [
    { slug: "andorra-la-vella", name: "Andorra la Vella" },
    { slug: "escaldes-engordany", name: "Escaldes-Engordany" },
    { slug: "encamp", name: "Encamp" },
    { slug: "sant-julia-de-loria", name: "Sant Julià de Lòria" },
  ],
  "san-marino": [
    { slug: "san-marino", name: "San Marino" },
    { slug: "serravalle", name: "Serravalle" },
    { slug: "borgo-maggiore", name: "Borgo Maggiore" },
    { slug: "domagnano", name: "Domagnano" },
  ],
  liechtenstein: [
    { slug: "vaduz", name: "Vaduz" },
    { slug: "schaan", name: "Schaan" },
    { slug: "balzers", name: "Balzers" },
    { slug: "eschen", name: "Eschen" },
    { slug: "triesen", name: "Triesen" },
  ],
  kyrgyzstan: [
    { slug: "bishkek", name: "Bishkek" },
    { slug: "osh", name: "Osh" },
    { slug: "jalalabad", name: "Jalal-Abad" },
    { slug: "karakol", name: "Karakol" },
    { slug: "naryn", name: "Naryn" },
  ],
  tajikistan: [
    { slug: "dushanbe", name: "Dushanbe" },
    { slug: "khujand", name: "Khujand" },
    { slug: "kulob", name: "Kulob" },
    { slug: "qurghonteppa", name: "Qurghonteppa" },
    { slug: "istaravshan", name: "Istaravshan" },
  ],
  turkmenistan: [
    { slug: "ashgabat", name: "Ashgabat" },
    { slug: "turkmenabat", name: "Turkmenabat" },
    { slug: "mary", name: "Mary" },
    { slug: "balkanabat", name: "Balkanabat" },
    { slug: "dashoguz", name: "Dashoguz" },
  ],
  uzbekistan: [
    { slug: "tashkent", name: "Tashkent" },
    { slug: "samarkand", name: "Samarkand" },
    { slug: "bukhara", name: "Bukhara" },
    { slug: "namangan", name: "Namangan" },
    { slug: "andijan", name: "Andijan" },
  ],
};
